package sg.telin.backend.model.iface;
import javax.persistence.Basic;


/** 
 * Object interface mapping for hibernate-handled table: product_code.
 * @author autogenerated
 */

public interface IProductCode {



    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: productCodeDesc.
	 * @return A String object (this.productCodeDesc)
	 */
	String getProductCodeDesc();
	

  
    /**  
     * Set the value related to the column: productCodeDesc.
	 * @param productCodeDesc the productCodeDesc value you wish to set
	 */
	void setProductCodeDesc(final String productCodeDesc);

    /**
     * Return the value associated with the column: productCodeShortDesc.
	 * @return A String object (this.productCodeShortDesc)
	 */
	String getProductCodeShortDesc();
	

  
    /**  
     * Set the value related to the column: productCodeShortDesc.
	 * @param productCodeShortDesc the productCodeShortDesc value you wish to set
	 */
	void setProductCodeShortDesc(final String productCodeShortDesc);

    /**
     * Return the value associated with the column: telinHk12.
	 * @return A String object (this.telinHk12)
	 */
	String getTelinHk12();
	

  
    /**  
     * Set the value related to the column: telinHk12.
	 * @param telinHk12 the telinHk12 value you wish to set
	 */
	void setTelinHk12(final String telinHk12);

    /**
     * Return the value associated with the column: telinJkt11.
	 * @return A String object (this.telinJkt11)
	 */
	String getTelinJkt11();
	

  
    /**  
     * Set the value related to the column: telinJkt11.
	 * @param telinJkt11 the telinJkt11 value you wish to set
	 */
	void setTelinJkt11(final String telinJkt11);

    /**
     * Return the value associated with the column: telkom.
	 * @return A String object (this.telkom)
	 */
	String getTelkom();
	

  
    /**  
     * Set the value related to the column: telkom.
	 * @param telkom the telkom value you wish to set
	 */
	void setTelkom(final String telkom);

    /**
     * Return the value associated with the column: thirdParties.
	 * @return A String object (this.thirdParties)
	 */
	String getThirdParties();
	

  
    /**  
     * Set the value related to the column: thirdParties.
	 * @param thirdParties the thirdParties value you wish to set
	 */
	void setThirdParties(final String thirdParties);

	// end of interface
}