package sg.telin.backend.model.iface;
import javax.persistence.Basic;


/** 
 * Object interface mapping for hibernate-handled table: product_map.
 * @author autogenerated
 */

public interface IProductMap {



    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: licenseFee.
	 * @return A Integer object (this.licenseFee)
	 */
	String getLicenseFee();
	

  
    /**  
     * Set the value related to the column: licenseFee.
	 * @param licenseFee the licenseFee value you wish to set
	 */
	void setLicenseFee(final String licenseFee);

    /**
     * Return the value associated with the column: mainProduct.
	 * @return A String object (this.mainProduct)
	 */
	String getMainProduct();
	

  
    /**  
     * Set the value related to the column: mainProduct.
	 * @param mainProduct the mainProduct value you wish to set
	 */
	void setMainProduct(final String mainProduct);

    /**
     * Return the value associated with the column: prodcutMapUnit.
	 * @return A String object (this.prodcutMapUnit)
	 */
	String getProdcutMapUnit();
	

  
    /**  
     * Set the value related to the column: prodcutMapUnit.
	 * @param prodcutMapUnit the prodcutMapUnit value you wish to set
	 */
	void setProdcutMapUnit(final String prodcutMapUnit);

    /**
     * Return the value associated with the column: productCode.
	 * @return A String object (this.productCode)
	 */
	String getProductCode();
	

  
    /**  
     * Set the value related to the column: productCode.
	 * @param productCode the productCode value you wish to set
	 */
	void setProductCode(final String productCode);

    /**
     * Return the value associated with the column: productGroup.
	 * @return A String object (this.productGroup)
	 */
	String getProductGroup();
	

  
    /**  
     * Set the value related to the column: productGroup.
	 * @param productGroup the productGroup value you wish to set
	 */
	void setProductGroup(final String productGroup);

    /**
     * Return the value associated with the column: productMapCategory.
	 * @return A String object (this.productMapCategory)
	 */
	String getProductMapCategory();
	

  
    /**  
     * Set the value related to the column: productMapCategory.
	 * @param productMapCategory the productMapCategory value you wish to set
	 */
	void setProductMapCategory(final String productMapCategory);

    /**
     * Return the value associated with the column: productMapGst.
	 * @return A String object (this.productMapGst)
	 */
	String getProductMapGst();
	

  
    /**  
     * Set the value related to the column: productMapGst.
	 * @param productMapGst the productMapGst value you wish to set
	 */
	void setProductMapGst(final String productMapGst);

    /**
     * Return the value associated with the column: revGlCode.
	 * @return A String object (this.revGlCode)
	 */
	String getRevGlCode();
	

  
    /**  
     * Set the value related to the column: revGlCode.
	 * @param revGlCode the revGlCode value you wish to set
	 */
	void setRevGlCode(final String revGlCode);

    /**
     * Return the value associated with the column: stdListPrice.
	 * @return A String object (this.stdListPrice)
	 */
	String getStdListPrice();
	

  
    /**  
     * Set the value related to the column: stdListPrice.
	 * @param stdListPrice the stdListPrice value you wish to set
	 */
	void setStdListPrice(final String stdListPrice);

	// end of interface
}