package sg.telin.backend.model.iface;
import javax.persistence.Basic;


/** 
 * Object interface mapping for hibernate-handled table: user.
 * @author autogenerated
 */

public interface IUser {



    /**
     * Return the value associated with the column: email.
	 * @return A String object (this.email)
	 */
	String getEmail();
	

  
    /**  
     * Set the value related to the column: email.
	 * @param email the email value you wish to set
	 */
	void setEmail(final String email);

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
	Integer getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final Integer id);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

    /**
     * Return the value associated with the column: username.
	 * @return A String object (this.username)
	 */
	String getUsername();
	

  
    /**  
     * Set the value related to the column: username.
	 * @param username the username value you wish to set
	 */
	void setUsername(final String username);

	// end of interface
}