package sg.telin.backend.model;

import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.proxy.HibernateProxy;

import sg.telin.backend.model.iface.IProductCode;


/** 
 * Object mapping for hibernate-handled table: product_code.
 * @author autogenerated
 */

@Entity
@Table(name = "product_code", catalog = "test")
public class ProductCode implements Cloneable, Serializable, IPojoGenEntity, IProductCode {

	/** Serial Version UID. */
	private static final long serialVersionUID = -559017560L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, String> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, String>());
	
	/** hashCode temporary storage. */
	private volatile String hashCode;
	

	/** Field mapping. */
	private String id;
	/** Field mapping. */
	private String productCodeDesc;
	/** Field mapping. */
	private String productCodeShortDesc;
	/** Field mapping. */
	private String telinHk12;
	/** Field mapping. */
	private String telinJkt11;
	/** Field mapping. */
	private String telkom;
	/** Field mapping. */
	private String thirdParties;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public ProductCode() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public ProductCode(String id) {
		this.id = id;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return ProductCode.class;
	}
 

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
    @Id 
	@Basic( optional = false )
	@Column( name = "product_code", nullable = false, length = 3  )
	public String getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final String id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
		SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: productCodeDesc.
	 * @return A String object (this.productCodeDesc)
	 */
	@Basic( optional = true )
	@Column( name = "product_code_desc", length = 20  )
	public String getProductCodeDesc() {
		return this.productCodeDesc;
		
	}
	

  
    /**  
     * Set the value related to the column: productCodeDesc.
	 * @param productCodeDesc the productCodeDesc value you wish to set
	 */
	public void setProductCodeDesc(final String productCodeDesc) {
		this.productCodeDesc = productCodeDesc;
	}

    /**
     * Return the value associated with the column: productCodeShortDesc.
	 * @return A String object (this.productCodeShortDesc)
	 */
	@Basic( optional = true )
	@Column( name = "product_code_short_desc", length = 20  )
	public String getProductCodeShortDesc() {
		return this.productCodeShortDesc;
		
	}
	

  
    /**  
     * Set the value related to the column: productCodeShortDesc.
	 * @param productCodeShortDesc the productCodeShortDesc value you wish to set
	 */
	public void setProductCodeShortDesc(final String productCodeShortDesc) {
		this.productCodeShortDesc = productCodeShortDesc;
	}

    /**
     * Return the value associated with the column: telinHk12.
	 * @return A String object (this.telinHk12)
	 */
	@Basic( optional = true )
	@Column( name = "telin_hk12", length = 20  )
	public String getTelinHk12() {
		return this.telinHk12;
		
	}
	

  
    /**  
     * Set the value related to the column: telinHk12.
	 * @param telinHk12 the telinHk12 value you wish to set
	 */
	public void setTelinHk12(final String telinHk12) {
		this.telinHk12 = telinHk12;
	}

    /**
     * Return the value associated with the column: telinJkt11.
	 * @return A String object (this.telinJkt11)
	 */
	@Basic( optional = true )
	@Column( name = "telin_jkt11", length = 20  )
	public String getTelinJkt11() {
		return this.telinJkt11;
		
	}
	

  
    /**  
     * Set the value related to the column: telinJkt11.
	 * @param telinJkt11 the telinJkt11 value you wish to set
	 */
	public void setTelinJkt11(final String telinJkt11) {
		this.telinJkt11 = telinJkt11;
	}

    /**
     * Return the value associated with the column: telkom.
	 * @return A String object (this.telkom)
	 */
	@Basic( optional = true )
	@Column( length = 20  )
	public String getTelkom() {
		return this.telkom;
		
	}
	

  
    /**  
     * Set the value related to the column: telkom.
	 * @param telkom the telkom value you wish to set
	 */
	public void setTelkom(final String telkom) {
		this.telkom = telkom;
	}

    /**
     * Return the value associated with the column: thirdParties.
	 * @return A String object (this.thirdParties)
	 */
	@Basic( optional = true )
	@Column( name = "third_parties", length = 20  )
	public String getThirdParties() {
		return this.thirdParties;
		
	}
	

  
    /**  
     * Set the value related to the column: thirdParties.
	 * @param thirdParties the thirdParties value you wish to set
	 */
	public void setThirdParties(final String thirdParties) {
		this.thirdParties = thirdParties;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public ProductCode clone() throws CloneNotSupportedException {
		
        final ProductCode copy = (ProductCode)super.clone();

		copy.setId(this.getId());
		copy.setProductCodeDesc(this.getProductCodeDesc());
		copy.setProductCodeShortDesc(this.getProductCodeShortDesc());
		copy.setTelinHk12(this.getTelinHk12());
		copy.setTelinJkt11(this.getTelinJkt11());
		copy.setTelkom(this.getTelkom());
		copy.setThirdParties(this.getThirdParties());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("id: " + this.getId() + ", ");
		sb.append("productCodeDesc: " + this.getProductCodeDesc() + ", ");
		sb.append("productCodeShortDesc: " + this.getProductCodeShortDesc() + ", ");
		sb.append("telinHk12: " + this.getTelinHk12() + ", ");
		sb.append("telinJkt11: " + this.getTelinJkt11() + ", ");
		sb.append("telkom: " + this.getTelkom() + ", ");
		sb.append("thirdParties: " + this.getThirdParties());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final ProductCode that; 
		try {
			that = (ProductCode) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getProductCodeDesc() == null) && (that.getProductCodeDesc() == null)) || (getProductCodeDesc() != null && getProductCodeDesc().equals(that.getProductCodeDesc())));
		result = result && (((getProductCodeShortDesc() == null) && (that.getProductCodeShortDesc() == null)) || (getProductCodeShortDesc() != null && getProductCodeShortDesc().equals(that.getProductCodeShortDesc())));
		result = result && (((getTelinHk12() == null) && (that.getTelinHk12() == null)) || (getTelinHk12() != null && getTelinHk12().equals(that.getTelinHk12())));
		result = result && (((getTelinJkt11() == null) && (that.getTelinJkt11() == null)) || (getTelinJkt11() != null && getTelinJkt11().equals(that.getTelinJkt11())));
		result = result && (((getTelkom() == null) && (that.getTelkom() == null)) || (getTelkom() != null && getTelkom().equals(that.getTelkom())));
		result = result && (((getThirdParties() == null) && (that.getThirdParties() == null)) || (getThirdParties() != null && getThirdParties().equals(that.getThirdParties())));
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					String newHashCode = null;

					if ( getId() != null ) {
					newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null ) {
							newHashCode = getId();
						} else {
						newHashCode = String.valueOf(super.hashCode());

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode.hashCode();
	}
	

	
}
