package sg.telin.backend.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.springframework.stereotype.Repository;

import sg.telin.backend.dao.ProductCodeDao;
import sg.telin.backend.model.ProductCode;
 
 
/**
 * DAO for table: ProductCode.
 * @author autogenerated
 */
@Repository
public class ProductCodeDaoImpl extends GenericHibernateDaoImpl<ProductCode, String> implements ProductCodeDao {
	
	/** Constructor method. */
		public ProductCodeDaoImpl() {
			super(ProductCode.class);
		}
	}

