package sg.telin.backend.dao.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.springframework.stereotype.Repository;

import sg.telin.backend.dao.UserDao;
import sg.telin.backend.model.User;
 
 
/**
 * DAO for table: User.
 * @author autogenerated
 */
@Repository
public class UserDaoImpl extends GenericHibernateDaoImpl<User, Integer> implements UserDao {
	
	/** Constructor method. */
		public UserDaoImpl() {
			super(User.class);
		}
	}

