package sg.telin.backend.dao;

import sg.telin.backend.model.ProductCode;

import com.felees.hbnpojogen.persistence.GenericDAO;
 
/**
 * DAO interface for table: ProductCode.
 * @author autogenerated
 */
public interface ProductCodeDao extends GenericDAO<ProductCode,  String>  {
	// constructor only
}

