package sg.telin.backend.dao;

import java.util.List;

import org.hibernate.Criteria;

import sg.telin.backend.model.ProductMap;

import com.felees.hbnpojogen.persistence.GenericDAO;
 
/**
 * DAO interface for table: ProductMap.
 * @author autogenerated
 */
public interface ProductMapDao extends GenericDAO<ProductMap,  Integer>  {
	// constructor only
	
	public Criteria createCriteria();
	public List<ProductMap> findByObject(ProductMap o);
}

