package sg.telin.backend.dao;

import sg.telin.backend.model.TestTable;

import com.felees.hbnpojogen.persistence.GenericDAO;
 
/**
 * DAO interface for table: TestTable.
 * @author autogenerated
 */
public interface TestTableDao extends GenericDAO<TestTable,  String>  {
	// constructor only
}

