package sg.telin.backend.dao;

import sg.telin.backend.model.User;

import com.felees.hbnpojogen.persistence.GenericDAO;
 
/**
 * DAO interface for table: User.
 * @author autogenerated
 */
public interface UserDao extends GenericDAO<User,  Integer>  {
	// constructor only
}

