package sg.telin.backend.test.factories;

import com.felees.hbnpojogen.randomlib.data.dataGeneration.*;
import org.springframework.stereotype.Component;

import sg.telin.backend.model.*;

import com.google.common.collect.ArrayListMultimap;
import com.google.common.collect.Multimap;
import java.util.Collection;

/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class TestDataPoolFactory {
	/** Table commit order. */
    private static final Multimap<String, String> tableDeps = ArrayListMultimap.create();
	/** DB commit order. */
	private static final String[] commitOrder = new String[]{"User"};
	static{
		// Store table deps for possible use. 
	}

    /**
     * Data pool factory for User.
     * @return UserA User object
     */
    public static User getUser() {

        User user = new User();    
        
        user.setEmail(BasicDataGenerator.generateRandomString(20));
        user.setId(BasicDataGenerator.generateRandomInt());
        user.setName(BasicDataGenerator.generateRandomString(20));
        user.setUsername(BasicDataGenerator.generateRandomString(20));

        return user;
    }
    /** Returns the commit order of this database. 
	 * Useful for iterating through the classes for deletion in the right order. 
	 * @return String[] list of classes
	 */
	public static String[] getDBCommitOrder() {
		return commitOrder;
	}
	
	/**
	 * @param className classname to return
	 * @return the tabledeps for the given class name
	 */
	public static Collection<String> getTabledeps(String className) {
		return tableDeps.get(className);
	}
	
}